version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - fredrikhr
  - package-ecosystem: npm
    directory: /scripts/THNETII.DotnetNew.WebStatic
    schedule:
      interval: daily
    reviewers:
      - fredrikhr
