version: 1
update_configs:
  - package_manager: "submodules"
    directory: /
    update_schedule: daily
    default_reviewers:
      - fredrikhr
    automerged_updates:
      - match:
          update_type: "all"
